apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    type: canary
    app: canary-deploy-new
  name: canary-deploy-new
  namespace: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      type: canary
      app: canary-deploy-new
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        type: canary
        app: canary-deploy-new
    spec:
      containers:
      - image: hakanyedibela/go-app:1.0.1
        name: go-app
        resources: {}
status: {}
