apiVersion: v1
kind: Namespace
metadata:
  name: canary
  labels:
    # Reject any Pod that doesn't meet the "restricted" Pod Security Standard.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
